name: Android pull-request CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decrypt keystores
        run: ./scripts/decrypt_debug_keystore.sh \
          && ./scripts/decrypt_alpha_keystore.sh \
          && ./scripts/decrypt_release_keystore.sh \
          && ./scripts/decrypt_properties_keystore.sh
        env:
          KEYSTORE_DEBUG_PASSPHRASE: ${{ secrets.KEYSTORE_DEBUG_PASSPHRASE }}
          KEYSTORE_ALPHA_PASSPHRASE: ${{ secrets.KEYSTORE_ALPHA_PASSPHRASE }}
          KEYSTORE_RELEASE_PASSPHRASE: ${{ secrets.KEYSTORE_RELEASE_PASSPHRASE }}
          KEYSTORE_PROPERTIES_PASSPHRASE: ${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}
      - name: Run tests
        run: ./gradlew app:testDebug
      - name: Build alpha and release
        run: ./gradlew app:assembleAlpha && ./gradlew app:assembleRelease
