name: Android ready-for-test CI

on:
  push:
    branches: [ ready-for-test ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decrypt keystores
        run: ./scripts/decrypt_alpha_keystore.sh \
          && ./scripts/decrypt_properties_keystore.sh
        env:
          KEYSTORE_ALPHA_PASSPHRASE: ${{ secrets.KEYSTORE_ALPHA_PASSPHRASE }}
          KEYSTORE_PROPERTIES_PASSPHRASE: ${{ secrets.KEYSTORE_PROPERTIES_PASSPHRASE }}
      - name: Build alpha
        run: ./gradlew app:assembleAlpha
      - name: Upload to firebase
        run: ./gradlew app:appDistributionUploadAlpha
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
